apiVersion: apps/v1
kind: Deployment
metadata:
  name: product_service
  labels:
    app: product_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product_service
  template:
    metadata:
      labels:
        app: product_service
    spec:
      imagePullSecrets:
        - name: acr-pull
      containers:
        - name: product_service
          image: ${ACR_LOGIN_SERVER}/product_service:${GITHUB_SHA}
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: product_service
spec:
  type: ClusterIP
  selector:
    app: product_service
  ports:
    - port: 8000
      targetPort: 8000
